POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "tokyoRamen",
	"name": "nafis bin",
	"password": "thisiscs101"
}

###
GET http://localhost:3003/api/users
###
POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "naruto",
	"name": "cook",
	"password": "onepiecegood"
}
